package corbaBanque;


/**
* corbaBanque/IBanqueRemoteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Banque.idl
* Monday, November 10, 2025 4:51:46 PM CET
*/


// --- Interface principale du service bancaire ---
public interface IBanqueRemoteOperations 
{

  // Créer un compte avec une somme initiale
  void creerCompte (corbaBanque.Compte cpte);

  // Verser une somme sur un compte existant
  void verser (int code, float mt);

  // Retirer une somme d�"un compte existant
  void retirer (int code, float mt);

  // Récupérer un compte à partir de son code
  corbaBanque.Compte getCompte (int code);

  // Récupérer la liste de tous les comptes
  corbaBanque.Compte[] getComptes ();

  // Convertir un montant (Euro -> Dinar Tunisien)
  double conversion (float mt);
} // interface IBanqueRemoteOperations
